[server]
# For local development, bind to localhost and use Streamlit's default port
headless = false
address = "localhost"
port = 8501

[theme]
primaryColor = "#ff6b6b"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
base = "dark"